# Generated by Django 2.1.5 on 2019-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('price', models.IntegerField(verbose_name='時給')),
                ('content', models.TextField(blank=True, null=True, verbose_name='案件詳細')),
            ],
            options={
                'db_table': 'work',
            },
        ),
    ]
