# Generated by Django 2.1.5 on 2019-02-15 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timewire', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
