# Generated by Django 2.1.5 on 2019-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timewire', '0003_work_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ユーザーID')),
                ('work_id', models.IntegerField(null=True, verbose_name='ジョブID')),
            ],
            options={
                'db_table': 'check',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='ユーザーID'),
        ),
    ]
